CREATE TABLE  "NURSE" 
   (	"EMPLOYEEID" NUMBER(4,0), 
	"NURSE NAME" VARCHAR2(15) NOT NULL ENABLE
	   ) ;


INSERT INTO  NURSE VALUES (888,'SEETHA');
INSERT INTO  NURSE VALUES (999,'SAMANTHA');
INSERT INTO  NURSE VALUES (111,'NAYANATHARA');
INSERT INTO  NURSE VALUES (222,'ANUSHKA');
INSERT INTO  NURSE VALUES (333,'ANUPAMA');
INSERT INTO  NURSE VALUES (444,'BHAVANI');
INSERT INTO  NURSE VALUES (555,'BHANU');
INSERT INTO  NURSE VALUES (666,'PAVANI');
INSERT INTO  NURSE VALUES (777,'KALYANI');
INSERT INTO  NURSE VALUES (100,'NAMRATHA');
INSERT INTO  NURSE VALUES (200,'DEEPIKA');
INSERT INTO  NURSE VALUES (300,'LORETTA');
INSERT INTO  NURSE VALUES (400,'EMILY');
INSERT INTO  NURSE VALUES (500,'HARITHA');
INSERT INTO  NURSE VALUES (600,'SONAL');
INSERT INTO  NURSE VALUES (700,'UMA');
INSERT INTO  NURSE VALUES (800,'PRANATHI');
INSERT INTO  NURSE VALUES (900,'PREETHI');
INSERT INTO  NURSE VALUES (150,'PRIYANKA');
INSERT INTO  NURSE VALUES (250,'KAJAL');