CREATE TABLE  "RECEPTIONIST" 
   (	"EMPLOYEEID" NUMBER(4,0), 
	"RECEPTIONIST NAME" VARCHAR2(15) NOT NULL ENABLE
	   ) ;


INSERT INTO RECEPTIONIST VALUES (987,'akshay');
INSERT INTO RECEPTIONIST VALUES (654,'mahaveer');
INSERT INTO RECEPTIONIST VALUES (599,'ram');
INSERT INTO RECEPTIONIST VALUES (423,'rakesh');
INSERT INTO RECEPTIONIST VALUES (951,'prasad');
INSERT INTO RECEPTIONIST VALUES (159,'srimanth');
INSERT INTO RECEPTIONIST VALUES (753,'douglas');
INSERT INTO RECEPTIONIST VALUES (357,'aravind');
INSERT INTO RECEPTIONIST VALUES (963,'calvin');
INSERT INTO RECEPTIONIST VALUES (369,'sadiya');
INSERT INTO RECEPTIONIST VALUES (258,'amulya');
INSERT INTO RECEPTIONIST VALUES (208,'geethika');
INSERT INTO RECEPTIONIST VALUES (705,'shravya');
INSERT INTO RECEPTIONIST VALUES (644,'pratyusha');
INSERT INTO RECEPTIONIST VALUES (588,'chandana');
INSERT INTO RECEPTIONIST VALUES (775,'niharika');
INSERT INTO RECEPTIONIST VALUES (636,'ravi');
INSERT INTO RECEPTIONIST VALUES (759,'tanmay');
INSERT INTO RECEPTIONIST VALUES (954,'bindu');
INSERT INTO RECEPTIONIST VALUES (632,'mahima');